- name: copy1
  copy: src=/data/soft/ansible/software/jdk-8u161-linux-x64.tar.gz dest=/root

- name: mkdir
  command: mkdir -p /data/soft

- name: copy2
  command: cp /root/jdk-8u161-linux-x64.tar.gz /data/soft/

- name: tar
  command: chdir=/data/soft tar -xf jdk-8u161-linux-x64.tar.gz

- name: profile
  shell: echo {{item}} >> /etc/profile && source /etc/profile
  with_items:
         - export JAVA_HOME=/data/soft/jdk1.8.0_161
         - export PATH=\$JAVA_HOME/bin:\$PATH
         - export CLASSPATH=.:\$JAVA_HOME/lib/tools.jar:\$JAVA_HOME/lib/dt.jar:\$CLASSPATH
